{
 "title": "NEAR - Staking stats",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total stake operation per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(EPOCH FROM to_date(CONCAT(extract(day from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(month from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(year from to_timestamp(receipt_included_in_block_timestamp / 10^9))), 'DD/MM/YYYY')) as time, \r\n    COUNT(*) as total_stake_ops\r\n    FROM public.action_receipt_actions\r\n\tWHERE receipt_receiver_account_id LIKE '%.pool.f863973.m0'\r\n\tAND args->>'method_name' = 'deposit_and_stake'\r\n\tAND action_kind = 'FUNCTION_CALL'\r\n\tAND $__unixEpochNanoFilter(receipt_included_in_block_timestamp)\r\n\tGROUP BY CONCAT(extract(day from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(month from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(year from to_timestamp(receipt_included_in_block_timestamp / 10^9)))\r\n\tORDER BY EXTRACT(EPOCH FROM to_date(CONCAT(extract(day from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(month from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(year from to_timestamp(receipt_included_in_block_timestamp / 10^9))), 'DD/MM/YYYY'));"
    }
   ]
  },
  {
   "title": "Total stakers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(EPOCH FROM to_date(CONCAT(extract(day from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(month from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(year from to_timestamp(receipt_included_in_block_timestamp / 10^9))), 'DD/MM/YYYY')) as time, \r\n    COUNT(DISTINCT(receipt_predecessor_account_id)) as total_stakers\r\n    FROM public.action_receipt_actions\r\n\tWHERE receipt_receiver_account_id LIKE '%.pool.f863973.m0'\r\n\tAND args->>'method_name' = 'deposit_and_stake'\r\n\tAND action_kind = 'FUNCTION_CALL'\r\n\tAND $__unixEpochNanoFilter(receipt_included_in_block_timestamp)\r\n\tGROUP BY CONCAT(extract(day from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(month from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(year from to_timestamp(receipt_included_in_block_timestamp / 10^9)))\r\n\tORDER BY EXTRACT(EPOCH FROM to_date(CONCAT(extract(day from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(month from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(year from to_timestamp(receipt_included_in_block_timestamp / 10^9))), 'DD/MM/YYYY'));"
    }
   ]
  },
  {
   "title": "Total stake volume per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(EPOCH FROM to_date(CONCAT(extract(day from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(month from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(year from to_timestamp(receipt_included_in_block_timestamp / 10^9))), 'DD/MM/YYYY')) as time, \r\n    SUM(CAST (args->>'deposit' AS numeric)) / 10^24 as total_stake_vol\r\n    FROM public.action_receipt_actions\r\n\tWHERE receipt_receiver_account_id LIKE '%.pool.f863973.m0'\r\n\tAND args->>'method_name' = 'deposit_and_stake'\r\n\tAND action_kind = 'FUNCTION_CALL'\r\n\tAND $__unixEpochNanoFilter(receipt_included_in_block_timestamp)\r\n\tGROUP BY CONCAT(extract(day from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(month from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(year from to_timestamp(receipt_included_in_block_timestamp / 10^9)))\r\n\tORDER BY EXTRACT(EPOCH FROM to_date(CONCAT(extract(day from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(month from to_timestamp(receipt_included_in_block_timestamp / 10^9)), '/', extract(year from to_timestamp(receipt_included_in_block_timestamp / 10^9))), 'DD/MM/YYYY'));"
    }
   ]
  }
 ]
}